### PR TITLE
draft: implement Feed and cookie login through auth folder

### PR DESCRIPTION
**Pull request by akarl10**
this is a aspx only prototype how to make the webfeed compatible with newer clients

see this issue: https://github.com/kimmknight/raweb/issues/6

the way this is supposed to work:
you copy the aspx version somewhere on your harddrive and add this folder as application in a website (or directly in wwwroot, the important thing is that it is a dedicated application)

on the auth folder (only that folder!) you should enable windows authentication and disable anonymous authentication
image

What is not implemented is protecting the download of rdp and ico/png files, but that files should not contain sensible data and additionally you would need to know the names

### CODE REVIEW

**Comment by kimmknight** [comment]
This is great and I'm keen to merge!

I've tested from:

- Web browser ✔️
- Latest Android RD Client ✔️
- Windows RemoteApp and Desktop Connections ✔️
- Windows RD Client app ❌ (Possibly a cert issue, need to test further)

I haven't yet tested:

- IOS RD Client app ❓

Even if there is still work to do to get Windows App and IOS App working, the current iteration isn't working with them anyway, so RAWeb would be no worse off by merging.

The only issue is:

In Default.aspx line 37/38 there is an extra `<%` which needs to be removed. Do you want to fix this up in your repo and make a new pull request?

**Comment by kimmknight** [comment]
I'm testing with ASP.NET 4.8 on Win 10 - Now seeing a new issue:

image

**Comment by akarl10** [comment]
> I'm testing with ASP.NET 4.8 on Win 10 - Now seeing a new issue:
> 
> image

sorry, now it should compile

**Comment by caraar12345** [comment]
Ha - good timing, just came to report exactly the same 😄 
It now redirects me to `/auth/loginfeed.aspx` where I can then authenticate with Windows credentials as expected.

Once authenticated, that URL just downloads `loginfeed.aspx` which contains a long hex number and that's it.

**Comment by akarl10** [comment]
> This is great and I'm keen to merge!
> 
> I've tested from:
> 
>     * Web browser ✔️
> 
>     * Latest Android RD Client ✔️
> 
>     * Windows RemoteApp and Desktop Connections ✔️
> 
>     * Windows RD Client app ❌ (Possibly a cert issue, need to test further)
> 
> 
> I haven't yet tested:
> 
>     * IOS RD Client app ❓
> 
> 
> Even if there is still work to do to get Windows App and IOS App working, the current iteration isn't working with them anyway, so RAWeb would be no worse off by merging.
> 
> The only issue is:
> 
> In Default.aspx line 37/38 there is an extra `<%` which needs to be removed. Do you want to fix this up in your repo and make a new pull request?

by windows rd client app you mean the app in the "app store"? Is that app really in use?

**Comment by kimmknight** [comment]
Awesome! Will test tomorrow. This is a big step up for RAWeb. 🙏

As for the "Windows RD Client app", yep, i mean the Microsoft App Store one. There's been some interest in getting that client working with RAWeb. It's not a priority, but I'm keen for completeness sake if nothing else.

I'll do some more testing on it. Also, there's the OSX client to consider.

**Comment by akarl10** [comment]
One thing to consider is that with this solution we don't get free impersonation as we get with windows authentication, so multiuser with file/folder permission will not work.

It might be possible when "saving" the impersonation in the token (but this can only be a "reference") and doing cleanups of thouse (don't know how to do that in aspx, but essentially we would need something like the session storage except that we would need to do this ourselfs since we cannot set cookies that the session thing relies on)

A possible solution to this problem might be: introduce a special subfolder "user\<username>" where to put user specific rdp files (essentially the folder would be user\computername\username or user\domain\username).
the same for group should be possible by putting the full membership in the "additional" field of the formlogintoken when creating it.
I think this is probably also easier to set up for the end user and you could use the same logic for rdpx (since there you probably don't have impersonation either)

**Comment by kimmknight** [comment]
Your update seems to be working well. I have tested in the same scenarios mentioned before with the same (good) results. I'll merge this.

**Comment by ScoobyCute** [comment]
can confirm, working for Mac RD Client:

- using "aspx" config
- using selfsigned cert, added to the mac
- only using windows authentication 
image

**Comment by ScoobyCute** [comment]
able to confirm on iOS too (Latest iOS and Windows (Remote Desktop App) version as of writing)
image

**Comment by kimmknight** [comment]
Thank you @ScoobyCute !!!! This is excellent news!

**Comment by akarl10** [comment]
if copilot can create a codesnippet that allows serializing that user token to a string that can be used in webfeed.aspx then that would absolutely work. I am no a Windows developer but my impression was when looking around that the "token" is a reference in the security subsystem, not some kind of signed password.

**Comment by kimmknight** [comment]
Latest update from Copilot after some discussion:

"My earlier suggestion about serializing and reusing the Windows token was flawed."

**Pull request merged**
