### PR TITLE
multiuser by folder

### PR DESCRIPTION
**Pull request by akarl10**
as already mentioned in https://github.com/kimmknight/raweb/pull/16 the "new" login is not compatible with the way multiuser is documented in the documetation here:

https://github.com/kimmknight/raweb/wiki/Configuring-RAWeb-for-a-multi-user-environment

this PR does not take this feature back but instead implements this feature by using subfolders in the rdp directory:

one for `user` one for `group`. the outermost folder are resources for every user.

### CODE REVIEW

**Comment by kimmknight** [comment]
Nice one! Just tested and it seems to work well.

I'm keen to implement subfolders (issue #14). With this in mind I think using security permissions remains the better approach for multi-user (rather than named folders). I don't, however, have much knowledge or experience with authentication in IIS or in general. Is there definitely no feasible way to get impersonation with the new auth mechanism?

**Comment by akarl10** [comment]
sure, security permission would be a nice and logical thing to do. That being said I don't know how to handle the passing of the impersonation to the .ASPXAUTH cookie that is essentially only a signed string, not an object storage.

the biggest issue with folders I see is not the security by itself (we could implement a get-resource.aspx that checks the permission and passes the file while denying direct access to the rdp folder) but the end user finding out what folders are searched. For that we might add a "whoami.aspx" that discloses every relevant path

**Comment by kimmknight** [comment]
> we could implement a get-resource.aspx that checks the permission and passes the file while denying direct access to the rdp folder

This!! Great idea! Do you think it's a big job?

**Comment by akarl10** [comment]
> > we could implement a get-resource.aspx that checks the permission and passes the file while denying direct access to the rdp folder
> 
> This!! Great idea! Do you think it's a big job?

building on top of having resource access by folder (like this pr would do it) it wouln't be too big of an issue.

Reading filesystem ACL entries would be much more complex (and the IUSR would need read access to everything)

**Comment by kimmknight** [comment]
Latest update from Copilot after some discussion:

"My earlier suggestion about serializing and reusing the Windows token was flawed."

**Comment by kimmknight** [comment]
The new release adopts this concept. I have integrated and adapted your code, but I had made too many changes to merge this pull request easily. Thanks heaps for the idea and code 🙏

**Pull request closed without merging**
